image: projectsforge/ubuntu-16.04-java8-oracle

stages:
  - build
  - test
  - deploy

before_script:
  # remove any previously deployed artifact
  - rm -rf /home/user/.m2/repository/org/projectsforge/ 

# build of master
build_job:
  stage: build
  only:
    - master
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
  tags:
    - docker

# build of the current branch state applied on latest state of the master branch
build_merge_job:
  stage: build
  except:
    - master
    - tags
  script:
    - git config user.email "gitlab@projectsforge.org"
    - git config user.name "GitLab CI"
    - git merge origin master --no-commit --no-ff
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
  tags:
    - docker
    
# sonar preview of the current branch state applied on latest state of the master branch
#test_sonar_preview_job:
#  stage: test
#  except:
#    - master
#    - tags
#  script:
#    - git config user.email "gitlab@projectsforge.org"
#    - git config user.name "GitLab CI"
#    - git merge origin master --no-commit --no-ff
#    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD "-Dsonar.host.url=https://sonar.projectsforge.org" -Dsonar.useWsCache=false -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
#    - sed  's/.*Total.*>\([0-9]\{1,3\}\)[ ]*%.*/Coverage = \1%/' target/site/jacoco/index.html
#  tags:
#    - docker

# sonar on the master
#test_sonar_job:
#  stage: test
#  only:
#    - master
#  script:
#    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD "-Dsonar.host.url=https://sonar.projectsforge.org" -Dsonar.useWsCache=false -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
#    - sed  's/.*Total.*>\([0-9]\{1,3\}\)[ ]*%.*/Coverage = \1%/' target/site/jacoco/index.html
#  tags:
#    - docker

# deploy master (should be a SNAPSHOT)
deploy_job:
  stage: deploy
  only:
    - master
  script:
    - mvn --batch-mode deploy -Dmaven.test.skip=true -Djacoco.skip=true
  tags:
    - docker

# deploy a tag as a release
deploy_tags_job:
  stage: deploy
  only:
    - tags
  script:
    - mvn --batch-mode org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=$CI_BUILD_TAG -DgenerateBackupPoms=false
    - mvn --batch-mode clean deploy -Dmaven.test.skip=true -Djacoco.skip=true 
  tags:
    - docker